[package]
name = "slate"
version = "0.1.0"
authors = ["Juan Hern√°ndez <juan.hernandez.babon@gmail.com>"]

[lib]
name = "slate"
path = "src/lib.rs"

[[bin]]
name = "slate"
path = "src/bin.rs"

[dependencies]
docopt = "0.6"
rustc-serialize = "0.3"
exec = "0.2.0"

[dev-dependencies]
rand = "0.3"
