[package]
name = "slate"
version = "0.1.0"
authors = ["Juan Hern√°ndez <juan.hernandez.babon@gmail.com>"]

[dependencies]
docopt = "0.6"
rustc-serialize = "0.3"  # if you're using `derive(RustcDecodable)`
